#### general settings
name: train_withSF
use_tb_logger: true
model: LLFlow
distortion: sr
scale: 1
gpu_ids: [0]
dataset: LoL
use_rot: true
optimize_all_z: false
cond_encoder: ConEncoder1
train_gt_ratio: 0.0
avg_color_map: false

concat_histeq: true
histeq_as_input: false
concat_color_map: false
gray_map: false # concat 1-input.mean(dim=1) to the input

align_condition_feature: false
align_weight: 0.001
align_maxpool: true

to_yuv: false

encode_color_map: false
le_curve: false
# sigmoid_output: true

#### datasets
datasets:
  train:
    quant: 32
    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 1
    use_flip: true
    use_detection: false
    color: RGB
    use_crop: true
    crop_size: 512 # 192
    # noise_prob: 0.20
    noise_prob: 0.2
    noise_level: 5
    log_low: False
    gamma_aug: false
  val:
    n_workers: 1
    quant: 32
    n_max: 20
    batch_size: 1 # must be 1
    log_low: False


heat: 0 # This is the standard deviation of the latent vectors
################ network structures ################
network_G:
  which_model_G: LLFlow
  in_nc: 3
  out_nc: 3
  nf: 32
  nb: 4 #  12 for our low light encoder, 23 for LLFlow
  train_RRDB: false
  train_RRDB_delay: 0.5
  flow:
    K: 4 # 24.49 psnr use12 # 16
    L: 3 # 4
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    conditionInFeaDim: 64
    split:
      enable: false
    fea_up0: true
    stackRRDB:
      blocks: [1]
      concat: true
